
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const MY_ORDER_SUCCESS = 'MY_ORDER_SUCCESS'
export const MY_ORDER_FAIL = 'MY_ORDER_FAIL'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'
export const PROVIDER_ORDER_SUCCESS = 'PROVIDER_ORDER_SUCCESS'
export const PROVIDER_ORDER_FAIL = 'PROVIDER_ORDER_FAIL'
export const UPDATE_PRICE_ORDER = 'UPDATE_PRICE_ORDER'



